### ISSUE TITLE
connect client to API

### ISSUE THREAD

**Issue by perennialAutodidact** [perennialAutodidact/memory-snap#26]
The React frontend needs to use the Express backend. Replace the Pexels API's `createClient` function within the `useFetchedPhotos` hook and replace it with a `fetch` call to the backend endpoint. Move all environment variables from the frontend to the backend. Setup tests with `msw`.

**Comment by russfraze** [comment]
I'm checking this out now. 

I see that the fetch call from the hook is now making a request to the backend. When I look at the app.js backend, I see the response contains the api key, but I'm not sure where the Pexels url end point comes in to play? 

Eventually whats returned form the api call will need to be returned by the hook for use in the rest of the frontend, correct?

**Comment by perennialAutodidact** [comment]
You're correct. It should return the photos from the API. Perhaps I forgot to push some commits. Let me check it out and I'll let you know.

**Comment by perennialAutodidact** [comment]
The call to the API is failing due to a missing environment variable containing the URL of the backend API. Adding `REACT_APP_API_URL=http://localhost:8080` to `packages/frontend/.env.local` should fix it.
