### ISSUE TITLE
Fetch photos for tiles

### ISSUE THREAD

**Issue by perennialAutodidact** [perennialAutodidact/memory-snap#31]
The tiles should render photos from the Pexels API via the backend server's `/photos` endpoint. Add a value to the photos context `quantity` and set its default value to `4`. Use the `quantity` value as the `perPage` parameter when making the API request. Then, render a `Tile` component for each photo using the `TileGrid` component. 

The photos should be stored in context and accessed from there for rendering the grid.

**Comment by russfraze** [comment]
I got this done on my working branch, I'll make a PR for it as soon as dev is back. 

![Image](https://github.com/perennialAutodidact/memory-snap/assets/81979567/31ca5c62-3ede-43bd-a275-fe512ca3cfa0)

**Comment by perennialAutodidact** [comment]
@russfraze If you wanted to make the GameProvider a child of the PhotosProvider in this ticket, I think that'd work.

**Comment by russfraze** [comment]
Sounds good.
