### ISSUE TITLE
TileGrid component - Tile images should be rendered in pairs

### ISSUE THREAD

**Issue by perennialAutodidact** [perennialAutodidact/memory-snap#4]
The number of required images is equal to half the number of tiles in the game. The goal of the game is to find matching pairs, so tiles will have to be rendered in sets of two. The tiles should still be rendered in random positions to keep the game fun. The point is that, despite their random positions, there is a match for each image in the grid.

Each tile object in the `GameContext` should have an item within it to keep track of the location of its matching companion. For instance, if the tile at row 0, column 1 matches the tile at row 1, column 0, the respective objects would look like this:

```javascript
// tiles.row[0].column[1]
{
  faceUp: false,
  isMatched: false,
  // add row/column of the companion tile
  companion: {
    row: 1,
    column: 0,
  }
}

// tiles.row[1].column[0]
{
  faceUp: false,
  isMatched: false,
  // add the row/column of the companion tile
  companion: {
    row: 0,
    column: 1,
  }
}
```

**Comment by perennialAutodidact** [comment]
Each tile object will have a unique id and the `companion` value just needs to point to the id of the matching tile.

**Comment by russfraze** [comment]
@perennialAutodidact we talked about deleting this issue. I think it's been covered already in a previous PR, and the idea of linking the tiles in this way isn't needed.
