### ISSUE TITLE
Install and setup `nodemon`

### ISSUE THREAD

**Issue by perennialAutodidact** [perennialAutodidact/memory-snap#44]
`nodemon` will enable hot-reloading of the backend code.
 
Install `nodemon` in the backend package: `yarn add nodemon --dev`

Add `"dev": "yarn run nodemon app.js"` to the "scripts" section of `package.json`

Edit: If possible, let's just replace the current "start" script for the backend instead of adding another script called "dev"

**Comment by Jangyaseni666** [comment]
I'd like to solve this issue.

**Comment by perennialAutodidact** [comment]
Awesome! Feel free to create a branch off of the `dev` branch and submit a PR when you're finished with a description of the changes and some steps detailing how to test the changes locally. Please let me know if you have any questions.

If I could ask, how did you find this particular issue?

**Comment by perennialAutodidact** [comment]
If you could, please name the feature branch `44-backend-install-and-setup-nodemon`. Thanks!

**Comment by perennialAutodidact** [comment]
I'm going to update the local setup instructions in the readme.
