### ISSUE TITLE
create setup form steps and routes

### ISSUE THREAD

**Issue by perennialAutodidact** [perennialAutodidact/memory-snap#49]
There are four form steps, one to retrieve each of the following:

- First player's name
- Second player's name
- Number of tiles
- Type of images

Consider a higher-order component to isolate repetitive styles, if necessary

Each will need a route and an `<Outlet/>` component will probably be needed for handling the nested routing.

The routes should have the following format: `/setup/step-{1-4}`

Don't build out each for step yet

**Comment by russfraze** [comment]
I'm looking at this and I'm wondering if mapping over the keys of the routes object will still work if we need to create nested routes for the steps in the setup route. I've been trying to think about this but cant seem to work it out so let me know what you think.

**Comment by russfraze** [comment]
@perennialAutodidact is this PR to just correctly set up the routes, or to also build the form components and their styling etc? Let me know and I can either keep doing that stuff on this PR or white a couple of new issues for the component / form design and higher order component. 

Currently I have the routes and steps object set up with the steps as nested routes within the setup route. 

If you go into the game context and chage the game stage to SETUP and change the step to ONE TWO THREE or FOUR you should see and H1 displayed in place of each form component.
