### ISSUE TITLE
Result Display Design Sketches

### ISSUE THREAD

**Issue by russfraze** [perennialAutodidact/memory-snap#84]
@perennialAutodidact 

I created a component called result display which comes up at the end of the game in place of the tile grid. There is an issue for the handling of game over, so for this issue it can just be how it looks and the info that is displayed. Here are two versions of the basic layout so far: 

![Screen Shot 2024-01-17 at 11 12 02 AM](https://github.com/perennialAutodidact/memory-snap/assets/81979567/2d6198ec-9505-4530-aa6e-84a59ab73f1d)
![Screen Shot 2024-01-17 at 11 04 30 AM](https://github.com/perennialAutodidact/memory-snap/assets/81979567/847f7f8b-9875-49a7-a550-ef0d87cd53df)

I'lll change it is to it's in the tie case. Let me know what you think and I can either make changes based on your feedback or if you want to make sketches thats cool too.

**Comment by perennialAutodidact** [comment]
I think that looks great. The tie case can probably just say "it's a tie!", though that will probably have to change if we're gonna allow more than two players, but that can come later. It'd also be cool to keep track of which pairs each player got and display them on that screen, but that can also come later.

**Comment by perennialAutodidact** [comment]
Might wanna link this issue with https://github.com/perennialAutodidact/memory-snap/issues/77
